name: Gold 24h

on:
  push:
    branches:
      - main
  schedule:
    - cron: '48 24 * * *'   # 06:48 giờ Hà Nội
    - cron: '48 4 * * *'    # 10:48 giờ Hà Nội
    - cron: '48 8 * * *'    # 14:48 giờ Hà Nội
    - cron: '48 11 * * *'   # 17:48 giờ Hà Nội
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run script
      run: |
        python gold.py  
